<img src = coverpage.png />

# NumPy

NumPy adalah salah satu library python yang berisikan operasi aljabar linear (matrix, array, dan operasi aljabar lain). Dalam data science, library ini merupakan salah satu library yang sering digunakan pada umumnya, pada modul ini akan diberikan penjelasan serta contoh syntax dengan menggunakan library NumPy.

Langkah pertama yaitu cara menggunakan library Python dengan meng-importnya pada modul. Pada sel dibawah ini akan dituliskan syntax import numpy dan agar mempersingkat syntax selanjutnya penggunaan kata syntax numpy akan disingkat menjadi np. 

In [1]:
import numpy as np

## NumPy Array

Dengan NumPy kita dapat membentuk sebuah array, dalam membuat array ada 2 metode, yaitu :
1. From Python List
2. Built-in Method

Dibawah ini akan dijelaskan bagaimana penerapan kedua metode tersebut.

### From Python List

Pada metode 'From Python List' array akan dibuat dari variabel bertipe list yang telah terbentuk, array akan menyesuaikan bentuk dimensi list, sehingga jika hendak membuat matrix berdimensi -n maka kita hanya perlu membuat list dengan dimensi -n, dan syntax yang digunakan adalah 'np.array()'.

In [2]:
#pendefinisian list
d1 = [1,2,3,4,5,6,7,8]
d2 = [[1,2,3],[2,3,1],[3,1,2]]
print('d1 = ',d1)
print('d2 = ',d2)

d1 =  [1, 2, 3, 4, 5, 6, 7, 8]
d2 =  [[1, 2, 3], [2, 3, 1], [3, 1, 2]]


In [3]:
#pembuatan array dimensi 1
arr1 = np.array(d1)
print(arr1)

[1 2 3 4 5 6 7 8]


In [4]:
#pembuatan array dimensi 2
arr2 = np.array(d2)
print(arr2)

[[1 2 3]
 [2 3 1]
 [3 1 2]]


### Built-in Method

Dengan metode ini, kita dapat membentuk array/matrix dengan syntax tertentu yang ada pada library NumPy. Berikut dibawah ini adalah beberapa syntax yang akan dicontohkan.
1. arange, untuk membuat array dengan parameter interval nilai dan kelipatan
2. zeros, untuk membuat matrix berdimensi -n dengan semua value adalah 0
3. ones, untuk membuat matrix berdimensi -n dengan semua value adalah 1
4. linspace, hampir sama dengan arange menggunakan parameter interval tetapi pada syntax ini dapat ditentukan banyaknya value yang ada diantara interval tersebut
5. eye, untuk membuat matrix identitas
6. random, untuk membuat array dengan isian acak

#### arange

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

#### zeros

In [7]:
np.zeros(2)

array([0., 0.])

In [8]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### ones

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### linspace

In [11]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [12]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

#### eye

In [14]:
np.eye(1)

array([[1.]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### random

Membuat isian array acak dengan nilai antara 0 dan 1

In [16]:
np.random.rand(5)

array([0.28928012, 0.11875684, 0.95036114, 0.81997704, 0.5157575 ])

In [17]:
np.random.rand(5,5)

array([[0.07086554, 0.95315047, 0.26135796, 0.25873369, 0.38337685],
       [0.6031066 , 0.72548239, 0.12461213, 0.27781384, 0.81326676],
       [0.87005786, 0.70182293, 0.5583879 , 0.02211822, 0.23551521],
       [0.0687235 , 0.32279961, 0.58613257, 0.87874287, 0.08127323],
       [0.96665951, 0.87789865, 0.746824  , 0.17423806, 0.74902116]])

Membuat isian array acak dengan nilai antara -1 dan 1

In [18]:
np.random.randn(5)

array([-0.569507  ,  0.08307391,  0.37316148,  0.37420881,  2.47250329])

In [19]:
np.random.randn(5,5)

array([[-0.95422533, -0.86825527,  0.39745572, -0.60248385,  0.32114415],
       [ 0.2396558 ,  1.4656246 ,  1.98026373, -0.07102081,  2.07139159],
       [-0.37354255, -0.28458182, -0.50434523, -0.4430942 , -1.83841681],
       [-1.4687732 ,  0.15928218,  1.41866564,  0.74465045,  0.01088016],
       [ 1.63267313, -0.23430123, -0.51973023, -1.33718151,  0.7028221 ]])

Membuat isian array bertipe bilangan interger dengan interval nilai sesuai parameter

In [20]:
np.random.randint(1,50)

44

In [21]:
np.random.randint(1,50,10)

array([ 9,  9, 13, 47, 36, 23, 35, 35,  5, 49])

## Selamat mencoba